---
title: "workMoney"
output: html_document
date: "2024-09-23"
editor_options: 
  chunk_output_type: console
---



```{r}
library(googlesheets4)
library(tidyverse)
library(openintro)
library(stringr)
gs4_auth(cache = ".secrets")

```

```{r}
sheet <- read_sheet('https://docs.google.com/spreadsheets/d/1T-t54HqWppRZarau4PHj6zLzL0Avpo_Aw7LmeLRu_GA/edit?gid=0')
```

```{r}
sheet$`Dates_worked` <- as.Date(sheet$`Dates_worked`)
sheet <- sheet%>%
  mutate(Year = year(`Dates_worked`))
ggplot(data = sheet, mapping = aes(y = `Total of the Night`)) +
  geom_boxplot() +
  facet_wrap(~Year) +
  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = seq(0, max(sheet$`Total of the Night`, na.rm = TRUE), by = 10))

ggplot(data = sheet, mapping = aes(x = `Total of the Night`)) +
  geom_histogram(binwidth = 8)

ggplot(data = sheet, mapping = aes(x = `Total of the Night`, y = `Online Tips`, colour = `Tip out`)) +
  geom_point() +
  scale_color_viridis_c(option = "H", direction = 1)

ggplot(data = sheet, mapping = aes(x = `Days Worked`, y = `Online Tips`, colour = `Sum of Tips`)) + 
  geom_point(size = 3) +
  facet_wrap(~`Day of Week`) +
  geom_vline(xintercept = 31) +
  scale_color_viridis_c(option = "H")+
  geom_smooth(method = "lm", color = "wheat", se = T)

sheet|>
  group_by(`Day of Week`)|>
  summarise(meanPerDay = mean(`Total of the Night`))
  

```

## 11/9/2024 Hypothesis testing for declining tipping culture
```{r}
oTips2023<-sheet|>
  filter((`Day of Week` == "1" |`Day of Week` == "2"| `Day of Week` == "3")& str_detect(Dates_worked, "2023"))|>
  select(`Day of Week`,`Online Tips`)

oTips2024<-sheet|>
  filter((`Day of Week` == "1" |`Day of Week` == "2"| `Day of Week` == "3")&str_detect(Dates_worked, "2024"))|>
  select(`Day of Week`,`Online Tips`)

oTipsVec2023<-oTips2023|>
  pull(`Online Tips`)

oTipsVec2024<-oTips2024|>
  pull(`Online Tips`)

oTips<-sheet|>
  filter(`Day of Week` == "1" |`Day of Week` == "2"| `Day of Week` == "3")

ggplot(data = oTips2023, mapping = aes(x = `Online Tips`)) +
  geom_histogram()

ggplot(data = oTips2024, mapping = aes(x = `Online Tips`)) +
  geom_histogram()




ts2023<-sd(oTipsVec2023)/sqrt(length(oTipsVec2023))
ts2024<- sd(oTipsVec2024)/sqrt(length(oTipsVec2024))
seHatP<- sqrt(ts2023^2 + ts2024^2)
mean2023<- mean(oTipsVec2023)
mean2024<- mean(oTipsVec2024)

testStat <- (mean2024 - mean2023)/seHatP

pval<- pt(testStat, length(oTipsVec2024)-1)


ggplot(data = oTips, mapping = aes(x = `Days Worked`, y = `Online Tips`, colour = `Sum of Tips`)) + 
  geom_point(size = 3) +
  facet_wrap(~`Day of Week`) +
  geom_vline(xintercept = 31) +
  scale_color_viridis_c(option = "H")+
  geom_smooth(method = "lm", color = "wheat", se = F)
```

##Ok lets do a simulation based test
```{r}
set.seed(111)
B<-10000

oTipsVec <- sheet|>
  filter(`Day of Week` == "1" |`Day of Week` == "2"| `Day of Week` == "3")|>
  select(`Online Tips`)|>
  pull()

bootMean<-rep(NA, B)

for(b in 1:B){
  oTipsSamp <- sample(oTipsVec)
  bootMean[b]<- mean(oTipsSamp[(length(oTipsVec2023)+1):(length(oTipsVec))]) - mean(oTipsSamp[1:length(oTipsVec2023)])
}

obsDiff<- mean2024 - mean2023

bootPVal <- sum(bootMean <= obsDiff)/B
```


